// src/components/api/endPoints.ts

const endPoints = {
  // Existing ones...
  login: "/auth/login",
  register: "/auth/register",
  applicantsRegister:
    "https://deutschemedizin-collage-backend-production.up.railway.app/api/applicants/register",
  registrarApplicantRegister: "/auth/register/student",
  studentStatus: "/student-statuses",
  academicYears: "/academic-years",
  attritionCauses: "/attrition-causes",
  batchClassSemsterYear: "/bcsy",
  applicantsList: "/applicants",
  applicantDetail: "/applicants/:id",
  applicantUpdateStatus: "/applicants/:id/status",
  applicantPhoto: "/applicants/:id/photo",
  applicantDocument: "/applicants/:id/document",
  students: "/students",
  studentsDeactivation: "/students/:id/disable",
  studentsActivation: "/students/:id/enable",
  createDepartmentHead: "/auth/create-department-head",
  createTeacher: "/auth/create-teacher",
  departmentHeads: "/department-heads",
  teachers: "/teachers",
  departments: "/departments",
  impairments: "/impairments",
  specificImpairtment: "/impairments/:id",
  singleImpairment: "/impairments/single",
  semesters: "/semesters",
  schoolBackgrounds: "/school-backgrounds",
  programModality: "/program-modality",
  classYears: "/class-years",
  semester: "/semesters",
  BatchClassYearSemesters: "/bcsy",
  batches: "/batches",
  singleBatch: "/batches/:id",
  courses: "/courses/single",
  allCourses: "/courses",
  courseById: "/courses/:id",
  regions: "/region",
  allWoreda: "/woreda",
  allZones: "/zone",
  allRegion: "/region",
  zonesByRegion: "/zone/region",
  woredasByZone: "/woreda/zone",
  notifications: "/notifications/me",
  notificationsLatest: "/notifications/me/latest",
  markNotificationRead: "/notifications/:id/read",
  markAllNotificationsRead: "/notifications/me/read-all",
  programLevels: "/program-levels",
  programLevelByCode: "/program-levels/:id",
  programModalities: "/program-modality",
  programModalityByCode: "/program-modality/:id",
};

export default endPoints;
